<p>There are several modifications that are recommended by the Council in order to best play MineZ and for best activity within the Watch:</p>
<ul>
    <li><a href="http://www.minecraftforum.net/topic/232701-">McPatccher</a> - A tool, not a mod.  Used to easily patch mods into the Minecraft jar, in the event ModLoader is being a bitch.</li>
    <li><a href="http://www.minecraftforum.net/topic/72747-">Faithful 32</a> - A 32-bit texture pack that keeps the Minecraftian feel.  Requires HD Textures.  Will work with provided JAR.</li>
    <li><a href="http://www.minecraftforum.net/topic/75440-">ModLoader</a> - A mod that helps other mods.  Most mods you install will need this.</li>
    <li><a href="http://www.minecraftforum.net/topic/482147-">Rei's Minimap</a> - Shows the miniature map that most other MineZ players use.  Allows you to set waypoints.</li>
    <li><a href="http://www.minecapes.net/">MineCapes</a> - Add the <a href="http://i.imgur.com/PW6NX.png">Night's Watch Cape</a> for immediate recognition amongst your peers.</li>
    <li><a href="http://www.minecraftforum.net/topic/986083-">FancyGUI</a> - Makes MineCraft's normal pages prettier, and gives you a nifty friend's list.</li>
</ul> 
<p>If you don't want to play with modding around, we've made a <a href="<?php echo $this->createUrl('site/modDownload'); ?>">a nifty minecraft.jar [1.3.1]</a> (<strong>Note:</strong> This jar is probably incompatible with anything you have in the <tt>mods</tt> folder.  If you are having problems, try renaming or moving your <tt>mods</tt> folder.) that has all of it for you - and don't worry!  It's protected.  You can only access it if you're a member of the watch and a Minecraft Premium user.  Just stick it in <tt><a href="file:///%APPDATA%/.minecraft/bin">%APPDATA%/.minecraft/bin</a></tt> (overwriting your previous installation) and you're ready to go!</p>
<p><small>Note: Our modified version also includes HD Textures, HD Font, Random Mobs, Custom Colors, Connected Textures, and Better Skies.</small></p> 